name: scomb_mobile
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# android version code
version: 2.5.12+35

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # web view
  flutter_inappwebview: ^5.7.0
  # http
  http: ^0.13.5
  html: ^0.15.1
  dio: ^4.0.6
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  # toast
  fluttertoast: ^8.1.1
  intl: ^0.17.0
  # icon
  flutter_native_splash: ^2.2.11
  flutter_launcher_icons: ^0.10.0
  cupertino_icons: ^1.0.5
  # db
  floor: ^1.3.0
  # open default browser
  url_launcher: ^6.1.6
  # color picker
  flutter_colorpicker: ^1.0.3
  # calendar
  table_calendar: ^3.0.7
  # notification
  flutter_local_notifications: ^12.0.2
  timezone: ^0.9.0
  # data time picker
  flutter_datetime_picker: ^1.5.1
  # slidable
  flutter_slidable: ^2.0.0
  # settings_ui
  settings_ui: ^2.0.2
  # app review
  app_review: ^2.1.2+1
  # charset_converter:
  charset_converter: ^2.1.0
  # encrypt
  encrypt: ^5.0.1
  # share
  share_plus: ^6.0.1
  path_provider: ^2.0.11
  file_picker: ^3.0.4

flutter_native_splash:
  image: "resources/splash.png"
  color: "F5F5F5"
flutter_icons:
  android: true
  ios: true
  image_path: "resources/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  # DB
  floor_generator: ^1.3.0
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - resources/
