name: scomb_mobile
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# android version code
version: 2.5.17+40

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # web view
  flutter_inappwebview: ^6.0.0
  # http
  http: ^1.2.1
  html: ^0.15.4
  dio: ^5.4.2+1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  # toast
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  # icon
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.6
  # db
  floor: ^1.4.2
  # open default browser
  url_launcher: ^6.2.6
  # color picker
  flutter_colorpicker: ^1.0.3
  # calendar
  table_calendar: ^3.1.1
  # notification
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  # data time picker
  flutter_datetime_picker_plus: ^2.1.0
  # slidable
  flutter_slidable: ^3.1.0
  # settings_ui
  settings_ui: ^2.0.2
  # app review
  in_app_review: ^2.0.9
  # charset_converter:
  charset_converter: ^2.2.0
  # encrypt
  encrypt: ^5.0.3
  # share
  share_plus: ^8.0.3
  path_provider: ^2.1.3
  file_picker: ^8.0.0+1

flutter_native_splash:
  image: "resources/splash.png"
  color: "F5F5F5"
flutter_icons:
  android: true
  ios: true
  image_path: "resources/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  # DB
  floor_generator: ^1.4.2
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - resources/
